import { CapturedImage } from '../types';

// URL Web App của Google Apps Script để nhận dữ liệu
const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbz2hIcKecqxYKmgiMDWG6qn6pzTt84nADQdRtgFvUECV-b2myS56bgBO1QXwlDrWXm-sg/exec"; 

export interface SheetData {
  stt: string; // Generated by timestamp or server
  tenNhanSu: string;
  tenThietBi: string;
  gioChup: string;
  diaDiem: string;
  imageBase64: string; // Script sẽ upload lên Drive và lấy link
}

export const sendToGoogleSheet = async (image: CapturedImage): Promise<boolean> => {
  if (!GOOGLE_SCRIPT_URL || GOOGLE_SCRIPT_URL.includes("YOUR_GOOGLE_APPS_SCRIPT")) {
    console.warn("Chưa cấu hình URL Google Apps Script. Dữ liệu sẽ không được gửi.");
    return false;
  }

  try {
    const formData = new FormData();
    
    // Chuẩn bị dữ liệu
    const timeStr = image.timestamp.toLocaleString('vi-VN');
    const locationStr = image.location?.address 
      ? `${image.location.address} (${image.location.lat.toFixed(6)}, ${image.location.lng.toFixed(6)})`
      : `${image.location?.lat}, ${image.location?.lng}`;

    // Tách base64 header để gửi raw data nếu cần, hoặc gửi nguyên chuỗi tùy backend xử lý
    // Ở đây ta gửi nguyên chuỗi, Backend (Apps Script) sẽ xử lý
    const finalImage = image.processedDataUrl || image.originalDataUrl;

    formData.append("tenNhanSu", image.personnelName);
    formData.append("tenThietBi", image.deviceName);
    formData.append("gioChup", timeStr);
    formData.append("diaDiem", locationStr);
    formData.append("base64Image", finalImage);

    // Sử dụng no-cors để tránh lỗi CORS khi gọi từ browser đến Google Script
    // Tuy nhiên, no-cors sẽ không trả về response body, nên ta chỉ có thể assume là gửi thành công nếu không có lỗi network.
    await fetch(GOOGLE_SCRIPT_URL, {
      method: "POST",
      body: formData,
      mode: "no-cors" 
    });

    console.log("Đã gửi yêu cầu đến Google Sheet");
    return true;
  } catch (error) {
    console.error("Lỗi khi gửi Google Sheet:", error);
    return false;
  }
};